package demo36.auto;

/** Class _DeptVO was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DeptVO extends org.apache.cayenne.CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String DEPT_CODE_PROPERTY = "deptCode";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String STATUS_PROPERTY = "status";

    public static final String DEPT_CODE_PK_COLUMN = "DEPT_CODE";

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }
    
    
    public void setDeptCode(String deptCode) {
        writeProperty("deptCode", deptCode);
    }
    public String getDeptCode() {
        return (String)readProperty("deptCode");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }
    
    
}
