package demo36.auto;

/** Class _TasksVO was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TasksVO extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String STATUS_PROPERTY = "status";
    public static final String TASK_CODE_PROPERTY = "taskCode";

    public static final String TASK_CODE_PK_COLUMN = "TASK_CODE";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }
    
    
    public void setTaskCode(String taskCode) {
        writeProperty("taskCode", taskCode);
    }
    public String getTaskCode() {
        return (String)readProperty("taskCode");
    }
    
    
}
